// Generates src/themes/index.js by inlining each src/themes/*.css file as an
// exported JavaScript string. Bundling the CSS as strings means the plugin never
// has to resolve a filesystem path at runtime, so it works identically under npm,
// pnpm, Yarn PnP, hoisted installs and monorepos.
//
// Run `npm run build:themes` after editing any theme CSS. It also runs
// automatically before publishing (see the `prepublishOnly` script).

const fs = require("fs");
const path = require("path");

const themesDir = path.join(__dirname, "..", "src", "themes");

// camelCase the file stem so `high-contrast.css` -> `highContrast`.
const toExportName = (file) =>
  file.replace(/\.css$/, "").replace(/-([a-z])/g, (_, c) => c.toUpperCase());

const files = fs
  .readdirSync(themesDir)
  .filter((file) => file.endsWith(".css"))
  .sort();

const lines = [
  "// AUTO-GENERATED by scripts/build-themes.js — do not edit by hand.",
  "// Run `npm run build:themes` after editing any src/themes/*.css file.",
  "",
];

for (const file of files) {
  const css = fs.readFileSync(path.join(themesDir, file), "utf8");
  lines.push(`export const ${toExportName(file)} = ${JSON.stringify(css)};`);
}

lines.push("");

fs.writeFileSync(path.join(themesDir, "index.js"), lines.join("\n"));
console.log(`Generated src/themes/index.js from ${files.length} theme(s).`);
